service: text-to-speech-backend

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  role: arn:aws:iam::249925989891:role/talking-app-role

functions:
  speak:
    handler: handler.speak
    events:
      - http:
          path: speak
          method: post
          cors: true
